# Generated by Django 5.0.2 on 2026-10-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=128)),
                ('comuna', models.CharField(max_length=64)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('horario', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
